language: node_js
node_js:
  - node
  - lts/*
  - 10
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm i --frozen-lockfile --no-verify-store-integrity
script:
  - pnpm run build:dev
  - pnpm test
  - pnpm run build:prod
after_success:
  - pnpm i -g codecov semantic-release
  - codecov --disable=gcov
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
